storage:
  type: ${storage:local}

local:
  urlPrefix: ${urlPrefix:"localhost:8080"}

token: ${token:hello}

management:
  influx:
    metrics:
      export:
        enabled: false
logging:
  level:
    root: info

spring:
  datasource:
    url: ${jdbcUrl}
    username: ${jdbcUser}
    password: ${jdbcPassword}
    driver-class-name: com.mysql.cj.jdbc.Driver

  threads:
    virtual:
      enabled: true