spring:
  data:
    mongodb:
      database: memes
      uri: ${mongoUri}
  threads:
    virtual:
      enabled: true
storage:
  type: ${storage}

local:
  urlPrefix: ${urlPrefix:"localhost:8080"}

qiniu:
  accessKey: ${ak}
  secretKey: ${sk}
  bucket: ${bucket}
  urlPrefix: ${urlPrefix}
  dirName: ${dirName}

token: ${token}

hnsw:
  dimension: 128
  m: 16
  efConstruction: 200
  efSearch: 200
  maxElements: 1000000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  influx:
    metrics:
      export:
        bucket: ${influxBucket}
        org: ${influxOrg}
        token: ${influxToken}
        enabled: true
        step: 10s
        retention-policy: autogen
        uri: ${influxUrl}
        auto-create-db: true
server:
  shutdown: graceful
