spring:
  data:
    mongodb:
      database: memes-dev
      host: ${mongoHost}
      port: ${mongoPort}
      username: ${mongoUser}
      password: ${mongoPassword}
      authentication-database: admin

storage:
  type: ${storage}

qiniu:
  accessKey: ${ak}
  secretKey: ${sk}
  bucket: ${bucket}
  urlPrefix: ${urlPrefix}


minio:
  endpoint: ${endpoint}
  accessKey: ${ak}
  secretKey: ${sk}
  bucket: ${bucket}
  urlPrefix: ${urlPrefix}

local:
  urlPrefix: ${urlPrefix}

token: ${token}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  influx:
    metrics:
      export:
        bucket: ${influxBucket}-dev
        org: ${influxOrg}
        token: ${influxToken}
        enabled: true
        step: 5s
        retention-policy: autogen
        uri: ${influxUrl}
        auto-create-db: true