storage:
  type: ${storage:local}

local:
  urlPrefix: ${urlPrefix:"localhost:8080"}

token: ${token:hello}

management:
  influx:
    metrics:
      export:
        enabled: false
logging:
  level:
    root: info
spring:
  datasource:
    driver-class-name: org.apache.ibatis.datasource.unpooled.UnpooledDataSource.DriverProxy

