spring:
  threads:
    virtual:
      enabled: true
storage:
  type: ${storage}

local:
  urlPrefix: ${urlPrefix:"localhost:8080"}

qiniu:
  accessKey: ${ak}
  secretKey: ${sk}
  bucket: ${bucket}
  urlPrefix: ${urlPrefix}
  dirName: ${dirName}

token: ${token}


management:
  endpoints:
    web:
      exposure:
        include: "*"
  influx:
    metrics:
      export:
        bucket: ${influxBucket}
        org: ${influxOrg}
        token: ${influxToken}
        enabled: true
        step: 10s
        retention-policy: autogen
        uri: ${influxUrl}
        auto-create-db: true
server:
  shutdown: graceful
