storage:
  type: ${storage:local}

local:
  urlPrefix: ${urlPrefix:"localhost:8080"}

token: ${token:hello}

management:
  influx:
    metrics:
      export:
        enabled: false

logging:
  config: classpath:logback-spring.xml
  file:
    name: logs/${spring.application.name}.log
  level:
    root: INFO
    org:
      springframework: INFO
      hibernate: WARN
    com:
      memes:
        schedule:
          AiReviewer: debug

spring:
  datasource:
    url: ${jdbcUrl}
    username: ${jdbcUser}
    password: ${jdbcPassword}
    driver-class-name: com.mysql.cj.jdbc.Driver

  threads:
    virtual:
      enabled: true