spring:
  data:
    mongodb:
      database: memes-dev
      uri: ${mongoUri}

storage:
  type: ${storage:local}

local:
  urlPrefix: ${urlPrefix:"localhost:8080"}

token: ${token:hello}

management:
  influx:
    metrics:
      export:
        enabled: false
logging:
  level:
    root: info
