spring:
  data:
    mongodb:
      database: memes-dev
      host: ${mongoHost}
      port: ${mongoPort}
      username: ${mongoUser}
      password: ${mongoPassword}
      authentication-database: admin

storage:
  type: ${storage}

local:
  urlPrefix: ${urlPrefix}

token: ${token}
