spring:
  data:
    mongodb:
      database: memes-dev
      host: 10.112.169.94
      port: 30332
      username: root
      password: root
      authentication-database: admin

storage:
  type: local

qiniu:
  accessKey: ${ak}
  secretKey: ${sk}
  bucket: ${bucket}
  urlPrefix: ${urlPrefix}

local:
  urlPrefix: ${urlPrefix}

token: ${token}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  influx:
    metrics:
      export:
        bucket: ${influxBucket}-dev
        org: ${influxOrg}
        token: ${influxToken}
        enabled: true
        step: 5s
        retention-policy: autogen
        uri: ${influxUrl}
        auto-create-db: true