spring:
  data:
    mongodb:
      database: memes-dev
      uri: ${mongoUri}

storage:
  type: ${storage:local}

local:
  urlPrefix: ${urlPrefix:"localhost:8080"}

token: ${token:hello}

hnsw:
  dimension: 128
  m: 16
  efConstruction: 200
  efSearch: 200
  maxElements: 1000000

management:
  influx:
    metrics:
      export:
        enabled: false
